//go:build integration

package api_test

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"backend/src/api"
	"backend/src/database"
	"backend/src/domain"

	"github.com/gorilla/mux"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupRegistrationCodeTest() (*database.MemberRepositoryPGX, *database.SessionCache, *mux.Router) {
	memberRepo := database.NewMemberRepositoryPGX(testPool)
	sessionCache := database.NewSessionCache(time.Hour)
	codeRepo := database.NewRegistrationCodeRepositoryPGX(testPool)
	handler := api.NewRegistrationCodeHandler(codeRepo)

	auth := api.AuthMiddleware(sessionCache, memberRepo)
	adminAuth := api.RequireRole("admin", auth)

	r := mux.NewRouter()
	r.Handle("/api/registration-codes", adminAuth(http.HandlerFunc(handler.CreateCode))).Methods("POST")
	r.Handle("/api/registration-codes", adminAuth(http.HandlerFunc(handler.ListCodes))).Methods("GET")
	r.Handle("/api/registration-codes/{id}", adminAuth(http.HandlerFunc(handler.DeleteCode))).Methods("DELETE")

	return memberRepo, sessionCache, r
}

// authCookie creates a member with the given role in the same session cache the
// router uses, and returns their session cookie.
func authCookie(t *testing.T, memberRepo *database.MemberRepositoryPGX, sessionCache *database.SessionCache, role string) *http.Cookie {
	t.Helper()
	member := createAuthMember(t, memberRepo, sessionCache)
	if role == "admin" {
		_, err := testPool.Exec(context.Background(), "UPDATE members SET role = 'admin' WHERE id = $1", member.ID)
		require.NoError(t, err)
	}
	session := domain.Session{MemberID: member.ID}
	require.NoError(t, sessionCache.Create(context.Background(), &session))
	return &http.Cookie{Name: "session_key", Value: session.SessionKey}
}

func doCodeReq(t *testing.T, r *mux.Router, method, path string, body []byte, cookie *http.Cookie) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(method, path, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	if cookie != nil {
		req.AddCookie(cookie)
	}
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	return w
}

func TestRegistrationCode_AdminCreate(t *testing.T) {
	defer cleanupMembers(t)
	memberRepo, sessionCache, r := setupRegistrationCodeTest()
	cookie := authCookie(t, memberRepo, sessionCache, "admin")

	body, _ := json.Marshal(domain.CreateRegistrationCodeRequest{Code: "ADMIN-007"})
	w := doCodeReq(t, r, "POST", "/api/registration-codes", body, cookie)
	assert.Equal(t, http.StatusCreated, w.Code)

	var resp domain.RegistrationCodeResponse
	require.NoError(t, json.NewDecoder(w.Body).Decode(&resp))
	assert.Equal(t, "ADMIN-007", resp.Code.Code)
	assert.Equal(t, "available", resp.Code.Status)
}

func TestRegistrationCode_AdminAutoGenerated(t *testing.T) {
	defer cleanupMembers(t)
	memberRepo, sessionCache, r := setupRegistrationCodeTest()
	cookie := authCookie(t, memberRepo, sessionCache, "admin")

	body, _ := json.Marshal(domain.CreateRegistrationCodeRequest{})
	w := doCodeReq(t, r, "POST", "/api/registration-codes", body, cookie)
	assert.Equal(t, http.StatusCreated, w.Code)

	var resp domain.RegistrationCodeResponse
	require.NoError(t, json.NewDecoder(w.Body).Decode(&resp))
	assert.NotEmpty(t, resp.Code.Code)
}

func TestRegistrationCode_ListAndDelete(t *testing.T) {
	defer cleanupMembers(t)
	memberRepo, sessionCache, r := setupRegistrationCodeTest()
	cookie := authCookie(t, memberRepo, sessionCache, "admin")

	codeRepo := database.NewRegistrationCodeRepositoryPGX(testPool)
	created, err := codeRepo.Create(context.Background(), "", "LIST-001")
	require.NoError(t, err)

	w := doCodeReq(t, r, "GET", "/api/registration-codes", nil, cookie)
	assert.Equal(t, http.StatusOK, w.Code)

	var list domain.RegistrationCodeListResponse
	require.NoError(t, json.NewDecoder(w.Body).Decode(&list))
	require.NotEmpty(t, list.Codes)
	assert.Equal(t, "LIST-001", list.Codes[0].Code)

	w = doCodeReq(t, r, "DELETE", "/api/registration-codes/"+created.ID, nil, cookie)
	assert.Equal(t, http.StatusOK, w.Code)

	var count int
	_ = testPool.QueryRow(context.Background(), "SELECT count(*) FROM registration_codes WHERE id = $1", created.ID).Scan(&count)
	assert.Equal(t, 0, count)
	assert.Equal(t, http.StatusOK, w.Code)
}

func TestRegistrationCode_DeleteNotFound(t *testing.T) {
	defer cleanupMembers(t)
	memberRepo, sessionCache, r := setupRegistrationCodeTest()
	cookie := authCookie(t, memberRepo, sessionCache, "admin")

	w := doCodeReq(t, r, "DELETE", "/api/registration-codes/00000000-0000-0000-0000-000000000001", nil, cookie)
	assert.Equal(t, http.StatusNotFound, w.Code)
}

func TestRegistrationCode_MemberForbidden(t *testing.T) {
	defer cleanupMembers(t)
	memberRepo, sessionCache, r := setupRegistrationCodeTest()
	cookie := authCookie(t, memberRepo, sessionCache, "member")

	body, _ := json.Marshal(domain.CreateRegistrationCodeRequest{Code: "NOPE"})
	w := doCodeReq(t, r, "POST", "/api/registration-codes", body, cookie)
	assert.Equal(t, http.StatusForbidden, w.Code)
}

func TestRegistrationCode_Unauthorized(t *testing.T) {
	defer cleanupMembers(t)
	_, _, r := setupRegistrationCodeTest()

	body, _ := json.Marshal(domain.CreateRegistrationCodeRequest{Code: "NOPE"})
	w := doCodeReq(t, r, "POST", "/api/registration-codes", body, nil)
	assert.Equal(t, http.StatusUnauthorized, w.Code)
}